In [54]:
import numpy as np
import pandas as pd

In [55]:
diamonds = pd.read_csv(r'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
# diamonds.head()

In [56]:
df = diamonds.copy()
diamonds

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [57]:
# Questions
#* basic problems
# todo 1. Read the CSV and display the first 5 and last 5 rows
# todo 2. Find the shape (rows & columns) and data types of the dataset
# todo 3. Get summary statistics for all numeric columns
# todo 4. Display unique values in the 'cut' column and count their occurrences
# todo 5. Calculate the mean price of diamonds for each cut type

In [58]:
# 1st done
# 2nd 
# print(diamonds.info())
# ! let's fix the datatypes to reduce the memory usage

# 3.5 MB => 3.2 MB => 2.3 MB 
diamonds.table = diamonds.table.astype('float16')
diamonds[['x','y','z']] = diamonds[['x','y','z']].astype('float16')
diamonds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float16
 6   price    53940 non-null  int64
 7   x        53940 non-null  float16
 8   y        53940 non-null  float16
 9   z        53940 non-null  float16
dtypes: float16(4), float64(2), int64(1), object(3)
memory usage: 2.9+ MB

In [59]:
diamonds.describe()

c:\Users\HP\anaconda3\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
c:\Users\HP\anaconda3\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
c:\Users\HP\anaconda3\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
c:\Users\HP\anaconda3\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,5.394000e+04,53940.000000,5.394000e+04,5.394000e+04,5.394000e+04
mean,0.797940,61.749405,inf,3932.799722,inf,inf,inf
std,0.474011,1.432621,2.234375e+00,3989.439738,1.121094e+00,1.142578e+00,7.055664e-01
min,0.200000,43.000000,4.300000e+01,326.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.400000,61.000000,5.600000e+01,950.000000,4.710938e+00,4.718750e+00,2.910156e+00
50%,0.700000,61.800000,5.700000e+01,2401.000000,5.699219e+00,5.710938e+00,3.529297e+00
75%,1.040000,62.500000,5.900000e+01,5324.250000,6.539062e+00,6.539062e+00,4.039062e+00
max,5.010000,79.000000,9.500000e+01,18823.000000,1.074219e+01,5.890625e+01,3.179688e+01

In [60]:
print(diamonds.table.agg(['min','max']))
diamonds[['x','y','z']].agg(['min','max'])

min    43.0
max    95.0
Name: table, dtype: float16

             x         y          z
min   0.000000   0.00000   0.000000
max  10.742188  58.90625  31.796875

In [61]:
diamonds.cut.value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [62]:
diamonds

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.949219,3.980469,2.429688
1,0.21,Premium,E,SI1,59.8,61.0,326,3.890625,3.839844,2.310547
2,0.23,Good,E,VS1,56.9,65.0,327,4.050781,4.070312,2.310547
3,0.29,Premium,I,VS2,62.4,58.0,334,4.199219,4.230469,2.630859
4,0.31,Good,J,SI2,63.3,58.0,335,4.339844,4.351562,2.750000
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.750000,5.761719,3.500000
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.691406,5.750000,3.609375
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.660156,5.679688,3.560547
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.148438,6.121094,3.740234
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.828125,5.871094,3.640625

In [63]:
# diamonds = diamonds.round({
#     "carat": 2,
#     "depth": 1,
#     "table": 1,
#     "x": 2,
#     "y": 2,
#     "z": 2
# })

diamonds
diamonds.carat = diamonds.carat.round(2)
diamonds

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.949219,3.980469,2.429688
1,0.21,Premium,E,SI1,59.8,61.0,326,3.890625,3.839844,2.310547
2,0.23,Good,E,VS1,56.9,65.0,327,4.050781,4.070312,2.310547
3,0.29,Premium,I,VS2,62.4,58.0,334,4.199219,4.230469,2.630859
4,0.31,Good,J,SI2,63.3,58.0,335,4.339844,4.351562,2.750000
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.750000,5.761719,3.500000
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.691406,5.750000,3.609375
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.660156,5.679688,3.560547
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.148438,6.121094,3.740234
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.828125,5.871094,3.640625