**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/grouping-and-sorting).**

---

# Introduction

In these exercises we'll apply groupwise analysis to our dataset.

Run the code cell below to load the data before running the exercises.

In [25]:
import pandas as pd

reviews = pd.read_csv("../input/wine-reviews/winemag-data-130k-v2.csv", index_col=0)
#pd.set_option("display.max_rows", 5)

from learntools.core import binder; binder.bind(globals())
from learntools.pandas.grouping_and_sorting import *
print("Setup complete.")

Setup complete.

# Exercises

## 1.
Who are the most common wine reviewers in the dataset? Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, and whose values count how many reviews each person wrote.

In [26]:
# Your code here
# reviews_written = reviews.groupby('taster_twitter_handle').size()
reviews_written = reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()

# Check your answer
q1.check()
# reviews.head()

Correct:


```python
reviews_written = reviews.groupby('taster_twitter_handle').size()
```
or
```python
reviews_written = reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()
```

In [27]:
#q1.hint()
# q1.solution()
grouped = reviews.groupby('country').apply(lambda grp : grp, include_groups=False)
grouped.head(2)

                                                    description  \
country
Argentina 16  Baked plum, molasses, balsamic vinegar and che...
          17  Raw black-cherry aromas are direct and simple ...

                      designation  points  price          province  region_1  \
country
Argentina 16                Felix      87   30.0             Other  Cafayate
          17  Winemaker Selection      87   13.0  Mendoza Province   Mendoza

             region_2        taster_name taster_twitter_handle  \
country
Argentina 16      NaN  Michael Schachner           @wineschach
          17      NaN  Michael Schachner           @wineschach

                                                          title variety  \
country
Argentina 16         Felix Lavaque 2010 Felix Malbec (Cafayate)  Malbec
          17  Gaucho Andino 2011 Winemaker Selection Malbec ...  Malbec

                     winery
country
Argentina 16  Felix Lavaque
          17  Gaucho Andino

## 2.
What is the best wine I can buy for a given amount of money? Create a `Series` whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that `4.0` dollars is at the top and `3300.0` dollars is at the bottom).

In [28]:
best_rating_per_price = reviews.groupby('price').points.max()

# Check your answer
q2.check()

Correct

In [29]:
#q2.hint()
#q2.solution()
reviews.groupby('country').count().head(5)

,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,
Argentina,3800,2902,3800,3756,3800,3747,0,3797,3797,3800,3800,3800
Armenia,2,2,2,2,2,0,0,2,2,2,2,2
Australia,2329,1640,2329,2294,2329,2327,0,2037,2037,2329,2329,2329
Austria,3345,2825,3345,2799,3345,0,0,3337,3337,3345,3345,3345
Bosnia and Herzegovina,2,1,2,2,2,0,0,2,1,2,2,2

In [30]:
# Here is one interesting stuff :-
# you can use value_counts() similar fucntionality using groupby()
# normal value_counts() approach
countries = reviews.country.value_counts().sort_index().sort_values(ascending = False)

# here is groupby() appraoch
c2 = reviews.groupby('country').count().description.sort_index().sort_values(ascending =False)

# you should observe that we first sorted in both index and then values (you can do 
# vice versa but order should be same). if you don't sort, the Index won't align
# ---
# if you check the count, 'china' and 'serbia', they have same count but different positon in series
# therefore sorting is need to get same index position in series
c2 ==  countries

country
US                        True
France                    True
Italy                     True
Spain                     True
Portugal                  True
Chile                     True
Argentina                 True
Austria                   True
Australia                 True
Germany                   True
New Zealand               True
South Africa              True
Israel                    True
Greece                    True
Canada                    True
Hungary                   True
Bulgaria                  True
Romania                   True
Uruguay                   True
Turkey                    True
Slovenia                  True
Georgia                   True
England                   True
Croatia                   True
Mexico                    True
Moldova                   True
Brazil                    True
Lebanon                   True
Morocco                   True
Peru                      True
Ukraine                   True
Macedonia                 True
Serbia                    True
Czech Republic            True
Cyprus                    True
India                     True
Switzerland               True
Luxembourg                True
Armenia                   True
Bosnia and Herzegovina    True
China                     True
Slovakia                  True
Egypt                     True
dtype: bool

## 3.
What are the minimum and maximum prices for each `variety` of wine? Create a `DataFrame` whose index is the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

In [31]:
price_extremes = reviews.groupby('variety').price.agg([min, max])

# Check your answer
q3.check()

/tmp/ipykernel_38/4085108108.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  price_extremes = reviews.groupby('variety').price.agg([min, max])
/tmp/ipykernel_38/4085108108.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  price_extremes = reviews.groupby('variety').price.agg([min, max])

Correct

In [32]:
# q3.hint()
# q3.solution()
# reviews.head(1)

## 4.
What are the most expensive wine varieties? Create a variable `sorted_varieties` containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [33]:
sorted_varieties = reviews.groupby('variety')['price'].agg(['min','max']).sort_values(['min','max'], ascending = [False, False])

# Check your answer
q4.check()

Correct

In [34]:
#q4.hint()
#q4.solution()
reviews.head(1)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia

## 5.
Create a `Series` whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the `taster_name` and `points` columns.

In [35]:
reviewer_mean_ratings = reviews.groupby('taster_name').points.mean()

# Check your answer
q5.check()

Correct

In [36]:
#q5.hint()
#q5.solution()

Are there significant differences in the average scores assigned by the various reviewers? Run the cell below to use the `describe()` method to see a summary of the range of values.

In [37]:
reviewer_mean_ratings.describe()

count    19.000000
mean     88.233026
std       1.243610
min      85.855422
25%      87.323501
50%      88.536235
75%      88.975256
max      90.562551
Name: points, dtype: float64

## 6.
What combination of countries and varieties are most common? Create a `Series` whose index is a `MultiIndex`of `{country, variety}` pairs. For example, a pinot noir produced in the US should map to `{"US", "Pinot Noir"}`. Sort the values in the `Series` in descending order based on wine count.

In [38]:
country_variety_counts = reviews.groupby(['country','variety']).variety.size().sort_values(ascending = False)

# Check your answer
q6.check()

Correct

In [39]:
q6.hint()
#q6.solution()
# reviews.head(1)

Hint: Use `groupby()`, and provide a list of columns to group by.  You may also find `size()` and `sort_values()` to be useful!

# Keep going

Move on to the [**data types and missing data**](https://www.kaggle.com/residentmario/data-types-and-missing-values).

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*